import '@/assets/app.scss';
import type { Metadata } from 'next';
import 'slick-carousel/slick/slick-theme.css';
import 'slick-carousel/slick/slick.css';
import '@/assets/scss/globals.css';

export const metadata: Metadata = {
  title: 'BlockUltra',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
};

import type { PropsWithChildren } from 'react';
import { RootStyleRegistry } from '@/components/RootStyle';

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={'font-jm font-medium text-base'}>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
